name: "Build and AniPriWeb"

on: [push]

env:
  AZURE_WEBAPP_NAME: anipriweb # set this to your applications name
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '6.0.x'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK $({env.NETCORE_VERSION})
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish APP for deploy
      run: dotnet publish --configuration Release --no-build --output  $({env.AZURE_WEBAPP_NAME}) 
    
    - name: 'Deploy to Azure web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: $({env.AZURE_WEBAPP_NAME})
        publish-profile: $({secrets.AZURE_WEBAPP_PUBLISH_PROFILE})
        package: $({env.AZURE_WEBAPP_PACKAGE_PATH})
        
    - name: Publish Artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: webapp
        path: $({secrets.AZURE_WEBAPP_PACKAGE_PATH})
        
      

